CREATE TABLE `ccl_posting` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`topicid` TINYTEXT NOT NULL,
	`forumid` TINYTEXT NOT NULL,
	`lastupdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `id` (`id`)
)
ENGINE=InnoDB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=2